[package]
name = "task_timer"
version = "0.1.0"
edition = "2024"

[dependencies]
notify = { version = "8.1.0", features = ["serde"] }
serde_json = "1.0.140"
serde = { version = "1.0.219", features = ["derive"] }
